openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /India:
    get:
      description: Get universities in India
      responses:
        "200":
          description: Successful response
  /United+States:
    get:
      description: Get universities in United+States
      responses:
        "200":
          description: Successful response
